# Generated by Django 4.2 on 2023-06-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_app", "0007_alter_recipe_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="recipe_app.tag"
            ),
        ),
    ]
